package:
  name: mdplifs
  version: "0.0.1"

source:
  path: ../..

build:
  number: 0

requirements:
  host:
    - python
    - setuptools

  run:
    - python
    - numpy
    - scipy
    - mdtraj
    - docopt

test:
  requires:
    - pytest
  imports:
    - mdplifs

about:
  home: add_url_here
  license: MIT License
